core/urls.py
from django.urls import path
from . import views
app_name = 'core'
urlpatterns = [
    path('', views.feriado),
    path('cadastro', views.cadastro, name='cadastro')
]

feriados/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('core.urls')),
]

core/models.py
from django.db import models

class FeriadoModel(models.Model):
    nome = models.CharField('Feriado', max_length=50)
    dia = models.IntegerField('Data')
    mes = models.IntegerField('Mês')
    modificado_em = models.DateTimeField(verbose_name='Modificado em', 
                                         auto_now_add=False,
                                         auto_now=True)
    
    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Feriado'
        verbose_name_plural = 'Feriados'
        ordering = ('mes','-dia')

core/forms.py
from django import forms
from django.core.exceptions import ValidationError


class FeriadoForm(forms.Form):
    nome = forms.CharField(max_length=50)
    dia = forms.IntegerField()
    mes = forms.IntegerField()
    
    def clean_nome(self):
        nome = self.cleaned_data['nome']
        return nome.upper()

    def clean_dia(self):
        dia = self.cleaned_data['dia']
        if dia <=0 or dia>31:
            raise ValidationError('Dia Inválido')
        return dia

    def clean_mes(self):
        mes = self.cleaned_data['mes']
        if mes <=0 or mes>12:
            raise ValidationError('Mês Inválido')
        return mes

core/views.py
from django.shortcuts import render
from core.models import FeriadoModel
from datetime import date
from .forms import FeriadoForm
def feriado(request):
    hoje = date.today()
    qs = FeriadoModel.objects.filter(mes=hoje.month)
    qs = qs.filter(dia=hoje.day)
    if len(qs) == 1:
        nome_feriado = qs[0].nome
        contexto = {'title':"Meu Feriado", 'feriado':True,
                'nome_feriado':nome_feriado}
    else: 
        contexto = {'title':"Meu Feriado", 'feriado':False}
    return render(request, 'feriado.html', contexto)

def cadastro(request):
    if request.method == 'POST':
        form_feriado = FeriadoForm(request.POST)
        if form_feriado.is_valid():
            feriado = FeriadoModel.objects.create(**form_feriado.cleaned_data)
            # Retorne uma resposta HTTP para o envio bem-sucedido do formulário
            return redirect('success_url')  # Substitua 'success_url' pelo URL desejado

    # Código para lidar com solicitações GET (opcional)
    else:
        form_feriado = FeriadoForm()

    contexto = {'form_feriado': FeriadoForm()}  # Supondo que 'contexto' seja um dicionário para o contexto do template
    return render(request, "cadastro.html", contexto)

core/templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Paula Masson Marangon">
    <title>Cadastro Feriado</title>
</head>
<body>
    <br><br>
    <form action="{% url 'core:cadastro' %}" novalidate method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <h3>Dados do Feriado</h3>

    Feriado: {{form_feriado.nome}}
    Dia: {{form_feriado.dia}}
    Mês: {{ form_feriado.mes}}
        
        <br>

        {% if field.errors %}
            <ul class="errors">
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    

    <center>
        <input type="submit" value="Cadastro"/>   
        
    </center>
</form>
{% if form_feriado.errors %}
{% for field in form_feriado %}
    {% for error in field.errors %}
        <strong>{{ error|escape }}</strong><br>
    {% endfor %}
{% endfor %}
{% endif %}

{% if form_feriado.errors %}
{% for field in form__feriado %}
    {% for error in field.errors %}
        <strong>{{ error|escape }}</strong>
    {% endfor %}
{% endfor %}
{% endif %}

{% for error in form_feriado.non_field_errors %}
<strong>{{ error|escape }}</strong></li>
{% endfor %}


</body>
</html>

core/templates/feriado.html
<!DOCTYPE html>
<html lang="pt_br">
    <head>
      <meta charset="UTF-8">
      <title>{{ title  }}</title>
    </head>
    <body>
      {% if feriado %}
        <h1>{{ nome_feriado  }}</h1>
      {% else %}
        <h1>Não tem feriado hoje</h1>
      {% endif %}
      
    </body>
</html> 